server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  port: 8180

# Configuracion de conexion a la base de datos MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
  
